In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df = pd.read_csv('homeprices (1).csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
# I wanted to replace null values with median val 
# if there is decimal values import math and use math.floor
import math
df.bedrooms.median()
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [10]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df['price']) #features = x (so that should be in 2D [[]] and y will be in series [])

LinearRegression()

In [14]:
print(reg.coef_)
print(reg.intercept_)

[  112.06244194 23388.88007794 -3231.71790863]
221323.00186540402


In [16]:
reg.predict(pd.DataFrame({
    'area': [3000],
    'bedrooms': [3],
    'age': [20]
}))

array([563042.60975297])

In [20]:
 112.06244194*3000 + 23388.88007794 * 3 - 3231.71790863*20 + 221323.00186540402 #y = m1x1 + m2x2 + m3x3 + b

563042.609746624

Interview scoresssss


In [28]:
fd = pd.read_csv('hiring.csv')
fd

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [30]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [32]:
from word2number import w2n

In [34]:
fd.rename(columns = {
    'test_score(out of 10)' : 't_score',
    'interview_score(out of 10)' : 'i_score'
}, inplace = True )
fd.head()

experience  t_score  i_score  salary($)
0        NaN      8.0        9      50000
1        NaN      8.0        6      45000
2       five      6.0        7      60000
3        two     10.0       10      65000
4      seven      9.0        6      70000

In [44]:
fd.experience = fd.experience.fillna('zero')
fd

experience  t_score  i_score  salary($)
0       zero      8.0        9      50000
1       zero      8.0        6      45000
2       five      6.0        7      60000
3        two     10.0       10      65000
4      seven      9.0        6      70000
5      three      7.0       10      62000
6        ten      NaN        7      72000
7     eleven      7.0        8      80000

In [66]:
import math 

test_median = math.floor(fd.t_score.median())
print(test_median)
interview_median = math.floor(fd.i_score.median())
print(interview_median)

8
7


In [74]:
fd.t_score = fd.t_score.fillna(test_median) #i am converting null values to median score 
fd

experience  t_score  i_score  salary($)
0       zero      8.0        9      50000
1       zero      8.0        6      45000
2       five      6.0        7      60000
3        two     10.0       10      65000
4      seven      9.0        6      70000
5      three      7.0       10      62000
6        ten      8.0        7      72000
7     eleven      7.0        8      80000

In [72]:
fd.i_score = fd.i_score.fillna(interview_median)
fd

experience  t_score  i_score  salary($)
0       zero      8.0        9      50000
1       zero      8.0        6      45000
2       five      6.0        7      60000
3        two     10.0       10      65000
4      seven      9.0        6      70000
5      three      7.0       10      62000
6        ten      8.0        7      72000
7     eleven      7.0        8      80000

In [104]:
#It is telling that i need to change experience columns from to string to int val 
fd.experience= fd.experience.astype(str)
fd.experience = fd.experience.apply(w2n.word_to_num)
fd

experience  t_score  i_score  salary($)
0           0      8.0        9      50000
1           0      8.0        6      45000
2           5      6.0        7      60000
3           2     10.0       10      65000
4           7      9.0        6      70000
5           3      7.0       10      62000
6          10      8.0        7      72000
7          11      7.0        8      80000

In [106]:
#Now that i have all filled null val, i need to train the model using sklear and fit
regg = linear_model.LinearRegression()
regg.fit(fd[['experience', 't_score', 'i_score']], fd['salary($)'])

LinearRegression()

In [112]:
regg.predict(pd.DataFrame({
    'experience' : [2],
    't_score' : [9],
    'i_score' : [6]
}))
# Now that i have predicted salary for 2yr exp, 9testscore, 6interview score

array([53205.96797671])

In [116]:
regg.predict(pd.DataFrame({
    'experience' : [12],
    't_score' : [10],
    'i_score' : [10]
}))
# Now that i have predicted salary for 12yr exp, 10testscore, 10interview score

array([92002.18340611])